//Created by Action Script Viewer - http://www.buraks.com/asv
package nz.co.resn.molehill.island {
    import flash.display3D.*;
    import flash.display3D.textures.*;
    import flash.geom.*;
    import com.adobe.utils.*;
    import __AS3__.vec.*;
    import nz.co.resn.molehill.base.*;

    public class Cube extends RenderObject3D {

        private static var modelInited:Boolean = false;
        private static var indexBuffer:IndexBuffer3D;
        private static var vertexBuffer:VertexBuffer3D;
        private static var indencies:Vector.<uint>;
        private static var vertices:Vector.<Number>;
        private static var vertexShaderAssembler:AGALMiniAssembler;
        private static var fragmentShaderAssembler:AGALMiniAssembler;
        private static var shaderProgram:Program3D;

        public var targetScale:Number = 1;
        private var scaleAccel:Number = 0.1;
        private var posDecel:Number = 0.999;
        protected var cubeMap:CubeTexture;
        protected var _rotVel:Vector3D;
        protected var _posVel:Vector3D;

        public function Cube(context3D:Context3D, cubeMap:CubeTexture):void{
            super(context3D);
            if (!(modelInited)){
                this.initModel();
            };
            this.cubeMap = cubeMap;
            this._indexBuffer = indexBuffer;
            this._vertexBuffer = vertexBuffer;
            this._indencies = indencies;
            this._vertices = vertices;
            this._vertexShaderAssembler = vertexShaderAssembler;
            this._fragmentShaderAssembler = fragmentShaderAssembler;
            this._shaderProgram = shaderProgram;
        }
        private function initModel():void{
            modelInited = true;
            vertices = new Vector.<Number>();
            indencies = new Vector.<uint>();
            this.createSkyCube(8, vertices, indencies);
            indexBuffer = context3D.createIndexBuffer(indencies.length);
            indexBuffer.uploadFromVector(indencies, 0, indencies.length);
            vertexBuffer = context3D.createVertexBuffer((vertices.length / 4), 4);
            vertexBuffer.uploadFromVector(vertices, 0, (vertices.length / 4));
            this.initPrograms();
        }
        override protected function initPrograms():void{
            vertexShaderAssembler = new AGALMiniAssembler();
            vertexShaderAssembler.assemble(Context3DProgramType.VERTEX, ("m44 op, va0, vc0\n" + "mov v0, va0\n"));
            fragmentShaderAssembler = new AGALMiniAssembler();
            fragmentShaderAssembler.assemble(Context3DProgramType.FRAGMENT, ("tex ft0, v0, fs0 <cube,linear,clamp,miplinear>\n" + "mov oc, ft0\n"));
            shaderProgram = context3D.createProgram();
            shaderProgram.upload(vertexShaderAssembler.agalcode, fragmentShaderAssembler.agalcode);
        }
        protected function createSkyCube(s:Number, v:Vector.<Number>, i:Vector.<uint>):void{
            var c:int;
            var d:int;
            var e:int;
            var a0:Number = 0;
            var a1:Number = 1;
            e = (c / 4);
            var _temp1 = c;
            c = (c + 1);
            var _local9 = _temp1;
            v[_local9] = -(s);
            var _temp2 = c;
            c = (c + 1);
            var _local10 = _temp2;
            v[_local10] = s;
            var _temp3 = c;
            c = (c + 1);
            var _local11 = _temp3;
            v[_local11] = s;
            var _temp4 = c;
            c = (c + 1);
            var _local12 = _temp4;
            v[_local12] = 1;
            var _temp5 = c;
            c = (c + 1);
            var _local13 = _temp5;
            v[_local13] = -(s);
            var _temp6 = c;
            c = (c + 1);
            var _local14 = _temp6;
            v[_local14] = s;
            var _temp7 = c;
            c = (c + 1);
            var _local15 = _temp7;
            v[_local15] = -(s);
            var _temp8 = c;
            c = (c + 1);
            var _local16 = _temp8;
            v[_local16] = 1;
            var _temp9 = c;
            c = (c + 1);
            var _local17 = _temp9;
            v[_local17] = -(s);
            var _temp10 = c;
            c = (c + 1);
            var _local18 = _temp10;
            v[_local18] = -(s);
            var _temp11 = c;
            c = (c + 1);
            var _local19 = _temp11;
            v[_local19] = s;
            var _temp12 = c;
            c = (c + 1);
            var _local20 = _temp12;
            v[_local20] = 1;
            var _temp13 = c;
            c = (c + 1);
            var _local21 = _temp13;
            v[_local21] = -(s);
            var _temp14 = c;
            c = (c + 1);
            var _local22 = _temp14;
            v[_local22] = -(s);
            var _temp15 = c;
            c = (c + 1);
            var _local23 = _temp15;
            v[_local23] = -(s);
            var _temp16 = c;
            c = (c + 1);
            var _local24 = _temp16;
            v[_local24] = 1;
            var _temp17 = d;
            d = (d + 1);
            var _local25 = _temp17;
            i[_local25] = (e + 0);
            var _temp18 = d;
            d = (d + 1);
            var _local26 = _temp18;
            i[_local26] = (e + 2);
            var _temp19 = d;
            d = (d + 1);
            var _local27 = _temp19;
            i[_local27] = (e + 1);
            var _temp20 = d;
            d = (d + 1);
            var _local28 = _temp20;
            i[_local28] = (e + 1);
            var _temp21 = d;
            d = (d + 1);
            var _local29 = _temp21;
            i[_local29] = (e + 2);
            var _temp22 = d;
            d = (d + 1);
            var _local30 = _temp22;
            i[_local30] = (e + 3);
            e = (c / 4);
            var _temp23 = c;
            c = (c + 1);
            var _local31 = _temp23;
            v[_local31] = s;
            var _temp24 = c;
            c = (c + 1);
            var _local32 = _temp24;
            v[_local32] = s;
            var _temp25 = c;
            c = (c + 1);
            var _local33 = _temp25;
            v[_local33] = -(s);
            var _temp26 = c;
            c = (c + 1);
            var _local34 = _temp26;
            v[_local34] = 1;
            var _temp27 = c;
            c = (c + 1);
            var _local35 = _temp27;
            v[_local35] = s;
            var _temp28 = c;
            c = (c + 1);
            var _local36 = _temp28;
            v[_local36] = s;
            var _temp29 = c;
            c = (c + 1);
            var _local37 = _temp29;
            v[_local37] = s;
            var _temp30 = c;
            c = (c + 1);
            var _local38 = _temp30;
            v[_local38] = 1;
            var _temp31 = c;
            c = (c + 1);
            var _local39 = _temp31;
            v[_local39] = s;
            var _temp32 = c;
            c = (c + 1);
            var _local40 = _temp32;
            v[_local40] = -(s);
            var _temp33 = c;
            c = (c + 1);
            var _local41 = _temp33;
            v[_local41] = -(s);
            var _temp34 = c;
            c = (c + 1);
            var _local42 = _temp34;
            v[_local42] = 1;
            var _temp35 = c;
            c = (c + 1);
            var _local43 = _temp35;
            v[_local43] = s;
            var _temp36 = c;
            c = (c + 1);
            var _local44 = _temp36;
            v[_local44] = -(s);
            var _temp37 = c;
            c = (c + 1);
            var _local45 = _temp37;
            v[_local45] = s;
            var _temp38 = c;
            c = (c + 1);
            var _local46 = _temp38;
            v[_local46] = 1;
            var _temp39 = d;
            d = (d + 1);
            var _local47 = _temp39;
            i[_local47] = (e + 0);
            var _temp40 = d;
            d = (d + 1);
            var _local48 = _temp40;
            i[_local48] = (e + 2);
            var _temp41 = d;
            d = (d + 1);
            var _local49 = _temp41;
            i[_local49] = (e + 1);
            var _temp42 = d;
            d = (d + 1);
            var _local50 = _temp42;
            i[_local50] = (e + 1);
            var _temp43 = d;
            d = (d + 1);
            var _local51 = _temp43;
            i[_local51] = (e + 2);
            var _temp44 = d;
            d = (d + 1);
            var _local52 = _temp44;
            i[_local52] = (e + 3);
            e = (c / 4);
            var _temp45 = c;
            c = (c + 1);
            var _local53 = _temp45;
            v[_local53] = -(s);
            var _temp46 = c;
            c = (c + 1);
            var _local54 = _temp46;
            v[_local54] = -(s);
            var _temp47 = c;
            c = (c + 1);
            var _local55 = _temp47;
            v[_local55] = -(s);
            var _temp48 = c;
            c = (c + 1);
            var _local56 = _temp48;
            v[_local56] = 1;
            var _temp49 = c;
            c = (c + 1);
            var _local57 = _temp49;
            v[_local57] = s;
            var _temp50 = c;
            c = (c + 1);
            var _local58 = _temp50;
            v[_local58] = -(s);
            var _temp51 = c;
            c = (c + 1);
            var _local59 = _temp51;
            v[_local59] = -(s);
            var _temp52 = c;
            c = (c + 1);
            var _local60 = _temp52;
            v[_local60] = 1;
            var _temp53 = c;
            c = (c + 1);
            var _local61 = _temp53;
            v[_local61] = -(s);
            var _temp54 = c;
            c = (c + 1);
            var _local62 = _temp54;
            v[_local62] = -(s);
            var _temp55 = c;
            c = (c + 1);
            var _local63 = _temp55;
            v[_local63] = s;
            var _temp56 = c;
            c = (c + 1);
            var _local64 = _temp56;
            v[_local64] = 1;
            var _temp57 = c;
            c = (c + 1);
            var _local65 = _temp57;
            v[_local65] = s;
            var _temp58 = c;
            c = (c + 1);
            var _local66 = _temp58;
            v[_local66] = -(s);
            var _temp59 = c;
            c = (c + 1);
            var _local67 = _temp59;
            v[_local67] = s;
            var _temp60 = c;
            c = (c + 1);
            var _local68 = _temp60;
            v[_local68] = 1;
            var _temp61 = d;
            d = (d + 1);
            var _local69 = _temp61;
            i[_local69] = (e + 0);
            var _temp62 = d;
            d = (d + 1);
            var _local70 = _temp62;
            i[_local70] = (e + 2);
            var _temp63 = d;
            d = (d + 1);
            var _local71 = _temp63;
            i[_local71] = (e + 1);
            var _temp64 = d;
            d = (d + 1);
            var _local72 = _temp64;
            i[_local72] = (e + 1);
            var _temp65 = d;
            d = (d + 1);
            var _local73 = _temp65;
            i[_local73] = (e + 2);
            var _temp66 = d;
            d = (d + 1);
            var _local74 = _temp66;
            i[_local74] = (e + 3);
            e = (c / 4);
            var _temp67 = c;
            c = (c + 1);
            var _local75 = _temp67;
            v[_local75] = -(s);
            var _temp68 = c;
            c = (c + 1);
            var _local76 = _temp68;
            v[_local76] = s;
            var _temp69 = c;
            c = (c + 1);
            var _local77 = _temp69;
            v[_local77] = s;
            var _temp70 = c;
            c = (c + 1);
            var _local78 = _temp70;
            v[_local78] = 1;
            var _temp71 = c;
            c = (c + 1);
            var _local79 = _temp71;
            v[_local79] = s;
            var _temp72 = c;
            c = (c + 1);
            var _local80 = _temp72;
            v[_local80] = s;
            var _temp73 = c;
            c = (c + 1);
            var _local81 = _temp73;
            v[_local81] = s;
            var _temp74 = c;
            c = (c + 1);
            var _local82 = _temp74;
            v[_local82] = 1;
            var _temp75 = c;
            c = (c + 1);
            var _local83 = _temp75;
            v[_local83] = -(s);
            var _temp76 = c;
            c = (c + 1);
            var _local84 = _temp76;
            v[_local84] = s;
            var _temp77 = c;
            c = (c + 1);
            var _local85 = _temp77;
            v[_local85] = -(s);
            var _temp78 = c;
            c = (c + 1);
            var _local86 = _temp78;
            v[_local86] = 1;
            var _temp79 = c;
            c = (c + 1);
            var _local87 = _temp79;
            v[_local87] = s;
            var _temp80 = c;
            c = (c + 1);
            var _local88 = _temp80;
            v[_local88] = s;
            var _temp81 = c;
            c = (c + 1);
            var _local89 = _temp81;
            v[_local89] = -(s);
            var _temp82 = c;
            c = (c + 1);
            var _local90 = _temp82;
            v[_local90] = 1;
            var _temp83 = d;
            d = (d + 1);
            var _local91 = _temp83;
            i[_local91] = (e + 0);
            var _temp84 = d;
            d = (d + 1);
            var _local92 = _temp84;
            i[_local92] = (e + 2);
            var _temp85 = d;
            d = (d + 1);
            var _local93 = _temp85;
            i[_local93] = (e + 1);
            var _temp86 = d;
            d = (d + 1);
            var _local94 = _temp86;
            i[_local94] = (e + 1);
            var _temp87 = d;
            d = (d + 1);
            var _local95 = _temp87;
            i[_local95] = (e + 2);
            var _temp88 = d;
            d = (d + 1);
            var _local96 = _temp88;
            i[_local96] = (e + 3);
            e = (c / 4);
            var _temp89 = c;
            c = (c + 1);
            var _local97 = _temp89;
            v[_local97] = s;
            var _temp90 = c;
            c = (c + 1);
            var _local98 = _temp90;
            v[_local98] = s;
            var _temp91 = c;
            c = (c + 1);
            var _local99 = _temp91;
            v[_local99] = -(s);
            var _temp92 = c;
            c = (c + 1);
            var _local100 = _temp92;
            v[_local100] = 1;
            var _temp93 = c;
            c = (c + 1);
            var _local101 = _temp93;
            v[_local101] = -(s);
            var _temp94 = c;
            c = (c + 1);
            var _local102 = _temp94;
            v[_local102] = s;
            var _temp95 = c;
            c = (c + 1);
            var _local103 = _temp95;
            v[_local103] = -(s);
            var _temp96 = c;
            c = (c + 1);
            var _local104 = _temp96;
            v[_local104] = 1;
            var _temp97 = c;
            c = (c + 1);
            var _local105 = _temp97;
            v[_local105] = s;
            var _temp98 = c;
            c = (c + 1);
            var _local106 = _temp98;
            v[_local106] = -(s);
            var _temp99 = c;
            c = (c + 1);
            var _local107 = _temp99;
            v[_local107] = -(s);
            var _temp100 = c;
            c = (c + 1);
            var _local108 = _temp100;
            v[_local108] = 1;
            var _temp101 = c;
            c = (c + 1);
            var _local109 = _temp101;
            v[_local109] = -(s);
            var _temp102 = c;
            c = (c + 1);
            var _local110 = _temp102;
            v[_local110] = -(s);
            var _temp103 = c;
            c = (c + 1);
            var _local111 = _temp103;
            v[_local111] = -(s);
            var _temp104 = c;
            c = (c + 1);
            var _local112 = _temp104;
            v[_local112] = 1;
            var _temp105 = d;
            d = (d + 1);
            var _local113 = _temp105;
            i[_local113] = (e + 0);
            var _temp106 = d;
            d = (d + 1);
            var _local114 = _temp106;
            i[_local114] = (e + 2);
            var _temp107 = d;
            d = (d + 1);
            var _local115 = _temp107;
            i[_local115] = (e + 1);
            var _temp108 = d;
            d = (d + 1);
            var _local116 = _temp108;
            i[_local116] = (e + 1);
            var _temp109 = d;
            d = (d + 1);
            var _local117 = _temp109;
            i[_local117] = (e + 2);
            var _temp110 = d;
            d = (d + 1);
            var _local118 = _temp110;
            i[_local118] = (e + 3);
            e = (c / 4);
            var _temp111 = c;
            c = (c + 1);
            var _local119 = _temp111;
            v[_local119] = -(s);
            var _temp112 = c;
            c = (c + 1);
            var _local120 = _temp112;
            v[_local120] = s;
            var _temp113 = c;
            c = (c + 1);
            var _local121 = _temp113;
            v[_local121] = s;
            var _temp114 = c;
            c = (c + 1);
            var _local122 = _temp114;
            v[_local122] = 1;
            var _temp115 = c;
            c = (c + 1);
            var _local123 = _temp115;
            v[_local123] = s;
            var _temp116 = c;
            c = (c + 1);
            var _local124 = _temp116;
            v[_local124] = s;
            var _temp117 = c;
            c = (c + 1);
            var _local125 = _temp117;
            v[_local125] = s;
            var _temp118 = c;
            c = (c + 1);
            var _local126 = _temp118;
            v[_local126] = 1;
            var _temp119 = c;
            c = (c + 1);
            var _local127 = _temp119;
            v[_local127] = -(s);
            var _temp120 = c;
            c = (c + 1);
            var _local128 = _temp120;
            v[_local128] = -(s);
            var _temp121 = c;
            c = (c + 1);
            var _local129 = _temp121;
            v[_local129] = s;
            var _temp122 = c;
            c = (c + 1);
            var _local130 = _temp122;
            v[_local130] = 1;
            var _temp123 = c;
            c = (c + 1);
            var _local131 = _temp123;
            v[_local131] = s;
            var _temp124 = c;
            c = (c + 1);
            var _local132 = _temp124;
            v[_local132] = -(s);
            var _temp125 = c;
            c = (c + 1);
            var _local133 = _temp125;
            v[_local133] = s;
            var _temp126 = c;
            c = (c + 1);
            var _local134 = _temp126;
            v[_local134] = 1;
            var _temp127 = d;
            d = (d + 1);
            var _local135 = _temp127;
            i[_local135] = (e + 0);
            var _temp128 = d;
            d = (d + 1);
            var _local136 = _temp128;
            i[_local136] = (e + 2);
            var _temp129 = d;
            d = (d + 1);
            var _local137 = _temp129;
            i[_local137] = (e + 1);
            var _temp130 = d;
            d = (d + 1);
            var _local138 = _temp130;
            i[_local138] = (e + 1);
            var _temp131 = d;
            d = (d + 1);
            var _local139 = _temp131;
            i[_local139] = (e + 2);
            var _temp132 = d;
            d = (d + 1);
            var _local140 = _temp132;
            i[_local140] = (e + 3);
        }
        override public function update():void{
            _scale = (_scale + ((this.targetScale - _scale) * this.scaleAccel));
            if (this.rotVel){
                rotation.x = (rotation.x + this.rotVel.x);
                rotation.y = (rotation.y + this.rotVel.y);
                rotation.z = (rotation.z + this.rotVel.z);
            };
            if (this.posVel){
                position.x = (position.x + this.posVel.x);
                position.y = (position.y + this.posVel.y);
                position.z = (position.z + this.posVel.z);
                this.posVel.x = (this.posVel.x * this.posDecel);
                this.posVel.y = (this.posVel.y * this.posDecel);
                this.posVel.z = (this.posVel.z * this.posDecel);
            };
        }
        override public function draw(t:Number=0, viewMatrix:Matrix3D=null, projectionMatrix:Matrix3D=null, transformMatrix:Matrix3D=null):void{
            if (transformMatrix == null){
                transformMatrix = new Matrix3D();
                transformMatrix.identity();
            };
            context3D.setProgram(_shaderProgram);
            context3D.setVertexBufferAt(0, _vertexBuffer, 0, Context3DVertexBufferFormat.FLOAT_4);
            context3D.setTextureAt(0, this.cubeMap);
            var newViewMatrix:Matrix3D = new Matrix3D();
            newViewMatrix.appendRotation(180, Vector3D.X_AXIS);
            newViewMatrix.append(viewMatrix);
            var newTransformMatrix:Matrix3D = new Matrix3D();
            newTransformMatrix.append(this.worldMatrix);
            newTransformMatrix.append(transformMatrix);
            renderMatrix = new Matrix3D();
            renderMatrix.append(newTransformMatrix);
            renderMatrix.append(newViewMatrix);
            renderMatrix.append(projectionMatrix);
            context3D.setProgramConstantsFromMatrix(Context3DProgramType.VERTEX, 0, renderMatrix, true);
            context3D.drawTriangles(_indexBuffer, 0, (_indencies.length / 3));
            context3D.setTextureAt(0, null);
            context3D.setVertexBufferAt(0, null);
        }
        public function get rotVel():Vector3D{
            return (this._rotVel);
        }
        public function set rotVel(value:Vector3D):void{
            this._rotVel = value;
        }
        public function get posVel():Vector3D{
            return (this._posVel);
        }
        public function set posVel(value:Vector3D):void{
            this._posVel = value;
        }
        override public function get scale():Number{
            return (super.scale);
        }
        override public function set scale(value:Number):void{
            super.scale = value;
            this.targetScale = value;
        }

    }
}//package nz.co.resn.molehill.island 
